name: Spell checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: codespell-project/actions-codespell@3c04c03694eb927ff908b8b5abfe9c58b239b0ae # master
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          skip: ./.git,go.mod,go.sum
          ignore_words_list: AtLeast,AtMost
