name: Spell checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: codespell-project/actions-codespell@3b7da264292a727fcdc4acdc9eaf9a5abb92ba10 # master
        with:
          check_filenames: true
          # When using this Action in other repos, the --skip option below can be removed
          skip: ./.git,go.mod,go.sum
          ignore_words_list: AtLeast,AtMost
